spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization-inclusion: non_null
    default-property-inclusion: non_null
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
http:
  port: 8080

file-upload:
  destination-dir:
  max-size:
  allowed-types:
password:
  min-length: 0
  max-length: 0
  salt-rounds: 0
api:
  errors:
    ID.001: Provided value is not a valid email address
    ID.002: Provided value is too short or too long
    ID.003: Password should have length between 6 and 128 characters, at least one uppercase letter, lowercase letter, digit and special character
    ID.004: Passwords are not match
    ID.011: This user name is already taken
    ID.012: This email address is already taken