app:
  version: 0.0.0
spring:
  mail:
    host: fake-provider
    port: 0
    username: fake-account
    password: fake-password
    debug: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
password:
  min-length: 1
  max-length: 100
  salt-rounds: 8
file-upload:
  destination-dir: src/main/resources/local
  max-size: 3145728
  allowed-types: image/png, application/pdf
account-verification:
  token-prefix: 'fwggw-'
  token-suffix: '-eqwrr'
  content-length: 3
  expires_in_minutes: 360
password-reset:
  token-prefix: 'R23R'
  token-suffix: '-WEG2'
  content-length: 3
  expires_in_minutes: 360
  pin-length: 3
jwt:
  secret: TestarrooSecret
  algorithm: HS256
  valid-time-in-minutes: 5
  type: Bearer
  cookie:
    name: test-token
    valid-time-in-minutes: 10
    domain: ''
api:
  host: 'localhost:8443'
