spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization-inclusion: non_null
    default-property-inclusion: non_null
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
http:
  port: 8080

file-upload:
  destination-dir: C:\Users\kj199\Documents
  max-size: 5242880 #5 MB
  allowed-types: image/png, image/jpg