spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enable: true
  datasource:
    url: jdbc:mysql://localhost:3316/example
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:local/keys/keyStore.p12
    key-store-password: P@ssw0rd