app:
  name: Identity Server
  description: Identity API for Konrad Jezierski's bachelors project
springdoc:
  api-docs:
    path: /swagger-json
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization-inclusion: non_null
    default-property-inclusion: non_null
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  spring:
    cache:
      cache-names: files, public-profiles
      redis:
        time-to-live: 1h
  mail:
    from: testmail@test.pl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
http:
  port: 8080

file-upload:
  destination-dir: ''
  max-size: ''
  allowed-types: ''
password:
  min-length: 0
  max-length: 0
  salt-rounds: 0
jwt:
  secret: ''
  algorithm: ''
  valid-time-in-minutes: 0
  cookie:
    name: ''
    valid-time-in-minutes: 0
api:
  host: ''
  errors:
    ID.001: Provided value is not a valid email address
    ID.002: Provided value is too short or too long
    ID.003: Password should have length between 6 and 128 characters, at least one uppercase letter, lowercase letter, digit and special character
    ID.004: Passwords are not match
    ID.005: This user name is already taken
    ID.006: This email address is already taken
    ID.007: Invalid verification PIN
    ID.008: PIN has been expired
    ID.009: User is already verified
    ID.010: Account is not verified. Please verify your account in order to sign in